### ISSUE TITLE
ResolvePackageNotFound:    - click_default_group==1.2=py_1

### ISSUE THREAD

**Issue by katkopera** [MetaSUB-CAMP/camp_short-read-quality-control#11]
Hi again, 
while creating conda environment with `conda env create -f configs/conda/short-read-quality-control.yaml` I get `Solving environment: failed

ResolvePackageNotFound: 
  - click_default_group==1.2=py_1
`

I guess click_default_group should be installed from pip and you do have "click-default-group==1.2.2" under software to be installed with pip but at the same time didn't remove "click_default_group=1.2=py_1" from dependencies which leads to the problem described.

I guess other modules may have the same problem.

**Comment by lauren-mak** [comment]
Fixed, and all environments will be updated in the upcoming versions. Thanks!
