### ISSUE TITLE
why remove adopter by fastp and AdapterRemoval?

### ISSUE THREAD

**Issue by yuvaramsingh94** [MetaSUB-CAMP/camp_short-read-quality-control#14]
hi,
   is it necessary to have both fastp and AdapterRemoval in our pipeline to remove adopters . will it be fine to use only fastp.

Thanks
yuvaram

**Comment by lauren-mak** [comment]
Hi! FastP was incorporated to remove low-quality bases, and AdapterRemoval to remove adapters. While they may have some overlap in terms of functionality, we believe that they are better at their respective primary functions than as all-in-one tools, hence the decision to include both.
