### ISSUE TITLE
fastp seems to be using up to 16 threads instead of 24)

### ISSUE THREAD

**Issue by rbtoscan** [MetaSUB-CAMP/camp_short-read-quality-control#15]
Hi,

while running the pipeline I got this warning in the logs:

<img width="852" alt="image" src="https://user-images.githubusercontent.com/87976680/229577409-0cf76b26-fa0e-4105-ae5f-298e57e7ad32.png">

It seems that fastp uses up to 16 threads, so allocating more than that probably leads to idle cores...?
An issue on that: https://github.com/OpenGene/fastp/issues/211

I guess we can simply change the number of cores for this top to 16 or less.

**Comment by lauren-mak** [comment]
Yes this is correct! I was unaware that `fastp` had this limit, and am not sure why. The maximum number of threads for `fastp` has been set to 16 in the next version of the module.
