### ISSUE TITLE
Problems to create conda environment

### ISSUE THREAD

**Issue by juanu** [MetaSUB-CAMP/camp_short-read-quality-control#17]
I had issues creating a new conda environment from the yaml file (short-read-quality-control.yaml).
To solve it, I had to remove:

```
- click-default-group=1.2=py_1
```
from the dependency list. This dependency is already requested on the same file using pip

```
- click-default-group==1.2.2
```

**Comment by lauren-mak** [comment]
Addressed in the latest push. Thanks for spotting this!
