### ISSUE TITLE
Running the test problem 

### ISSUE THREAD

**Issue by lmszydlowski** [MetaSUB-CAMP/camp_short-read-quality-control#19]
I installed the module and ran into an error while running the "python workflow/short-read-quality-control.py test"

In every case I receive the following error: 

Building DAG of jobs...
WorkflowError:
MissingInputException: Missing input files for rule init_statistics:
    output: /camp_short-read-quality-control/test_out/short_read_qc/4_summary/uhgg_read_stats.csv
    wildcards: sample=4_summary/uhgg
    affected files:
        /camp_short-read-quality-control/test_out/tmp/4_summary/uhgg_2.fastq.gz
        /camp_short-read-quality-control/test_out/tmp/4_summary/uhgg_1.fastq.gz
MissingInputException: Missing input files for rule init_statistics:
    output: /camp_short-read-quality-control/test_out/short_read_qc/uhgg_read_stats.csv
    wildcards: sample=uhgg
    affected files:
        /camp_short-read-quality-control/test_out/tmp/uhgg_1.fastq.gz
        /camp_short-read-quality-control/test_out/tmp/uhgg_2.fastq.gz
MissingInputException: Missing input files for rule step_statistics:
    output: /camp_short-read-quality-control/test_out/short_read_qc/4_summary/uhgg_read_stats.csv
    wildcards: step=4_summary, sample=uhgg
    affected files:
        /camp_short-read-quality-control/test_out/short_read_qc/4_summary/uhgg_2.fastq.gz
        /camp_short-read-quality-control/test_out/short_read_qc/4_summary/uhgg_1.fastq.gz

In test_out/tmp/ there were uhgg_1.fastq and uhgg_2.fastq files

I instead used "python workflow/short-read-quality-control.py -s configs/samples.csv -r configs/resources.yaml -p configs/parameters.yaml -d test_data/test_out/"

and test dataset was successfully processed.

**Comment by lauren-mak** [comment]
I've patched this issue in today's update so if you pull it, it should be fixed. Thanks for using it!
