### ISSUE TITLE
pytest fails due to hardcoded paths

### ISSUE THREAD

**Issue by yuvaramsingh94** [MetaSUB-CAMP/camp_short-read-quality-control#6]
hi,
The pytest fails because of the absolute path used for loading the configurations.

`/pbtech_mounts/homes064/lam4003/bin/camp_short-read-quality-control/.tests/unit/fastqc_post/data`

**Comment by b-tierney** [comment]
Hi -- thank you for the heads up -- cc @lauren-mak 

We'll get this cleaned up in the next release -- in the meantime, you should be able to still test on your system this using the example commands/the data in the repo

**Comment by lauren-mak** [comment]
This has been addressed in the latest update (version 0.7.0). Please pull it, go over the `README.md` to make sure the module has been set up properly, and see if it works. Thanks for using the CAMP short-read QC module!
