### ISSUE TITLE
issue due to multiqc output file path

### ISSUE THREAD

**Issue by yuvaramsingh94** [MetaSUB-CAMP/camp_short-read-quality-control#8]
Hi,
  The snakemake pipeline fails due to output file of multiqc rule not written to final_reports . in line no 330 to 332 the code is copying the multiqc output from `4_summary` to `final_reports`. but, the snakemake fails to recognize this and throws the following error before crashing. changing multiqc output from `4_summary` to `final_reports` and removing lines 330 to 332 works.

```
Building DAG of jobs...
MissingInputException in rule all  in line 43 of /data/yuvaram/CAMP/camp_short-read-quality-control/workflow/Snakefile:
Missing input files for rule all:
    affected files:
        /data/yuvaram/CAMP/workdir/short_read_qc/final_reports/post_multiqc_report.html
        /data/yuvaram/CAMP/workdir/short_read_qc/final_reports/pre_multiqc_report.html
```

**Comment by lauren-mak** [comment]
This has been addressed in the latest update (version 0.7.0). Please pull it, go over the `README.md` to make sure the module has been set up properly, and see if it works. Thanks for using the CAMP short-read QC module!
