### ISSUE TITLE
Issues running bbmap tools (solved)

### ISSUE THREAD

**Issue by rbtoscan** [MetaSUB-CAMP/camp_short-read-quality-control#9]
Hi,

I had issues running bbmap tools, namely repair and tadpole, when those are installed as standalone executables (install instruction step 3).

The issue was related to java, or lack thereof.  Even after installing java, the issues changed but did not vanish (something to do with not being able to find/load main class - similar error [here](https://www.biostars.org/p/354562/)).

The solve was to install bbmap via conda: `conda install -c bioconda bbmap`
And to add the executables path (from condas bin folder) for both tadpole and repair to the `configs/parameters.yaml`.

So I guess bbmap should be added to the .yaml file to correctly setup the conda env. 
Attaching a working example.
[readqcc_conda-setup-example.yaml.zip](https://github.com/MetaSUB-CAMP/camp_short-read-quality-control/files/10872923/readqcc_conda-setup-example.yaml.zip)

Thanks!

Best
Rodolfo

**Comment by katkopera** [comment]
Hi, I only had part of the problem: "Java not found error". After installing Java, the module was completed successfully. 

In the module's documentation, you could mention that Java is a prerequisite.

**Comment by lauren-mak** [comment]
The note about Java was added to the README, and the environment will be updated in the future. Thanks!
